### ISSUE TITLE
Multi architecture build for amd64 and arm64 (Apple M1 Chip)

### ISSUE THREAD

**Issue by nathan-duddles** [CIS548/docker-env#18] opened 2022-01-04 16:43 UTC
Recently, I've encountered issues when building the docker image from the Dockerfile and docker-setup.sh file. 

Following the instructions in the README for ARM64 Architecture, when running "docker-compose build mcit", the build does not complete because of hash sums not matching for some installations in docker-setup.sh. 

If I comment out all parts of the docker-setup.sh file after the line:

wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | apt-key add -

then the build is able to complete.

I believe the issue may have to do with my current internet, as I was able to build without problem in other locations.

I am not sure if others will encounter this issue, but I believe it would be best to do a multi-architecture build of the image for amd64 and arm64 so that Apple M1 users can also Pull the docker image and will not need to build it.

I am unable to build the multi-arch image because of the above issue.

@kuang-da , would you mind trying to build the multi-arch image and push it the course Dockerhub? I was able to follow tutorials online, such as [this one](https://dev.to/tidalmigrations/multi-cpu-architecture-container-images-how-to-build-and-push-them-on-docker-hub-or-any-other-registry-2981), using my own Docker hub account and some test Dockerfiles.

**Comment by kuang-da** [comment] 2022-01-05 03:04
I just pushed images for both amd64 and arm64 to [the docker hub](https://hub.docker.com/r/cis548/docker-env/tags).

I also updated the readme to take notes about how to build it. 

https://github.com/CIS548/docker-env/blob/master/README.md#for-tas-push-image-to-dockerhub

The images are built from Linux. I had an issue previously that the `buildx` only works on Linux and Windows WSL but had some errors on macOS. Not sure whether Docker has fixed it though.

**Comment by nathan-duddles** [comment] 2022-01-05 16:59
I've tested out the amd64 build by running docker pull on my Intel Mac. Perhaps we can ask TAs if anyone has access to an M1 Apple chip Mac to test out the set up process, perhaps also referring to my draft of the new Project 0: Description? See: [issue 13](https://github.com/CIS548/docker-env/issues/13)

**Comment by nathan-duddles** [comment] 2022-01-12 20:13
Issue with vim not installed in amd64 build @singhalshubh confirmed. See [piazza post](https://piazza.com/class/kwqmp88d55q4bd?cid=39)

**Comment by singhalshubh** [comment] 2022-01-16 01:59
Solution posted https://piazza.com/class/kwqmp88d55q4bd?cid=39, 
And tested on two machines, one on mine, and another confirmed by student with a zoom call. Please review it and let's close the issue! @kuang-da @nathan-duddles

**Comment by nathan-duddles** [comment] 2022-01-16 02:14
From the [piazza posts](https://piazza.com/class/kwqmp88d55q4bd?cid=39) it sounds like it is the instructions on [this website ](https://linoxide.com/how-to-install-vim-text-editor-on-ubuntu/) that worked for students. Can you confirm? And is it the first instructions, which are how to install via apt get? 

Step 1. Update the Ubuntu package database

$ sudo apt update

Step 2. Install Vim using apt

$ sudo apt install vim

Step 3. Check Vim version

$ vim --version


If this should work, then I can add something in the instructions to direct M1 Mac users to install Vim...

I am concerned that there may be other missing installations for the arm64 image. 

@singhalshubh  would you be able to check if the other necessary installations are there, such as gdb and valgrind? I believe the main listing of installations is in the [docker-setup.sh](https://github.com/CIS548/docker-env/blob/master/docker-setup.sh) file

**Comment by singhalshubh** [comment] 2022-01-16 02:54
Nope, its the instructions written on the piazza post by a student.

First, installed all this necessary prerequisite tools:
$ sudo apt install ncurses-dev
$ sudo apt install make
$ sudo apt install build-essential
And then, one by one:
$ wget https://github.com/vim/vim/archive/master.zip
$ sudo apt install unzip
$ unzip master.zip
$ cd vim-master
$ cd src/
$ ./configure
$ make
$ sudo make install

**Comment by singhalshubh** [comment] 2022-01-16 02:59
Hi, According to docker-setup.sh all 

emacs, wget, clang-10, gdb, valgrind, git, curl, vim, tmux, make, gcc, sudo, dialog

are working and are preinstalled in the image. For vim, we have to follow these steps as mentioned above.

**Comment by nathan-duddles** [comment] 2022-01-16 19:25
I guess my concern was that it looks like according to docker-setup.sh, vim should also be installed and working. Maybe there it was the only application that doesn't install successfully from the arm64 image, but this made me realize that we never tested out this arm64 image... I hope no students using an M1 apple chip find that they also don't have gdb, valgrind etc.

**Comment by singhalshubh** [comment] 2022-01-16 19:52
Yes, I tested it on MAC M1, i7 and Ubuntu. It works on these host OSs as a virtual OS as stated in the docker and following these steps should exclude this step of vim and replace it with the instructions given above only for MAC M1 because rest all have VIM installed(confirmed by a couple of students as well)

**Comment by singhalshubh** [comment] 2022-01-16 19:55
Tested means writing man <command_name> and then <command_name> and if it displayed some error in the later command, it would hv been uninstalled. But all showed errors of missing arguments which was the indication of proper installation of all prereqs in docker on M1 i7, Ubuntu(these two are fine with vims too), MAC M1.

**Comment by nathan-duddles** [comment] 2022-01-17 02:26
Great! Thank you for doing that testing, @singhalshubh !  I think we may want to try to fix the arm64 docker image next semester, so for now I can make a piazza post highlighting the issue and solution. Edit: I the number of people affected outside of the existing piazza thread is probably minuscule, so I think rather than posting something to the entire class, we can remember to direct anyone [here](https://piazza.com/class/kwqmp88d55q4bd?cid=39) if they ask about this, until we get this fixed.

**Comment by kuang-da** [comment] 2022-01-20 01:57
I made a new test script to check the installation of the packages. Can anyone check if the script works on M1 mac by giving errors? In the Intel system, it gives `OK`.

https://github.com/CIS548/docker-env/pull/20

**Comment by singhalshubh** [comment] 2022-01-20 02:09
Tested on MAC M1. It shows OK provided the vim installation instructions were followed as stated above. Not sure about the new container though.
<img width="652" alt="Screen Shot 2022-01-19 at 9 08 31 PM" src="https://user-images.githubusercontent.com/28309128/150253535-fb969b1c-5678-44d3-82b5-964e6dad1181.png">

**Comment by kuang-da** [comment] 2022-01-20 02:21
Ideally, it should give errors on the current M1 container. Hopefully, this could be a seed of the continuous integration test workflow.

**Comment by kuang-da** [comment] 2022-01-20 02:32
Related issue #3

**Comment by singhalshubh** [comment] 2022-02-09 01:43
@kuang-da I think we can safely close this issue. Build works on CI for docker, so M1 has nothing to do with this anymore.

**Comment by kuang-da** [comment] 2022-02-09 02:07
Sounds good! Close it. Thanks!

**Closed as completed by kuang-da** 2022-02-09 02:07 UTC
Labels: help wanted
